/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package editordetextoo;

/**
 *
 * @author ruthreyes
 */
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;

public class editortexto extends javax.swing.JFrame {

    /**
     * Creates new form editortexto
     */
    FileMetadata data;
    boolean enabled = false;

    public editortexto(FileMetadata data) {
        initComponents();

        this.data = data;
        Font fonts[] = GraphicsEnvironment.getLocalGraphicsEnvironment().getAllFonts();

        for (Font f : fonts) {
            fontCombo.addItem(f.getName());
        }

        fontCombo.setSelectedItem(data.fontName);
        enabled = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fontCombo = new javax.swing.JComboBox<>();
        sizeCombo = new javax.swing.JComboBox<>();
        choosecolor_button = new javax.swing.JButton();
        copyBtn = new javax.swing.JLabel();
        cutBtn = new javax.swing.JLabel();
        pasteBtn = new javax.swing.JLabel();
        boldBtn = new javax.swing.JLabel();
        italicBtn = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textEditor = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("American Typewriter", 0, 24)); // NOI18N
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font(".SF NS Text", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Editor de texto");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 378, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 40));

        jPanel4.setBackground(new java.awt.Color(217, 217, 217));
        jPanel4.setForeground(new java.awt.Color(217, 217, 217));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Fuente");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tamaño");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Color");

        fontCombo.setBackground(new java.awt.Color(255, 255, 255));
        fontCombo.setForeground(new java.awt.Color(0, 0, 0));
        fontCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fontComboItemStateChanged(evt);
            }
        });

        sizeCombo.setBackground(new java.awt.Color(255, 255, 255));
        sizeCombo.setForeground(new java.awt.Color(0, 0, 0));
        sizeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "58", "10", "12", "14", "28", "24", "32", "36", "48" }));
        sizeCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sizeComboItemStateChanged(evt);
            }
        });

        choosecolor_button.setForeground(new java.awt.Color(255, 255, 255));
        choosecolor_button.setText("Choose");
        choosecolor_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosecolor_buttonActionPerformed(evt);
            }
        });

        copyBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i/3.png"))); // NOI18N
        copyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                copyBtnMouseClicked(evt);
            }
        });

        cutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i/1.png"))); // NOI18N
        cutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cutBtnMouseClicked(evt);
            }
        });

        pasteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i/2 (1).png"))); // NOI18N
        pasteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pasteBtnMouseClicked(evt);
            }
        });

        boldBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i/B.png"))); // NOI18N
        boldBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boldBtnMouseClicked(evt);
            }
        });

        italicBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i/7.png"))); // NOI18N
        italicBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                italicBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                italicBtnMouseEntered(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i/10.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i/9.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i/11.png"))); // NOI18N

        textEditor.setBackground(new java.awt.Color(255, 255, 255));
        textEditor.setColumns(20);
        textEditor.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        textEditor.setForeground(new java.awt.Color(0, 0, 0));
        textEditor.setRows(5);
        jScrollPane1.setViewportView(textEditor);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i/12.png"))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i/13.png"))); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i/14.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cutBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(copyBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pasteBtn)
                        .addGap(60, 60, 60)
                        .addComponent(boldBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(italicBtn)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fontCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sizeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(choosecolor_button, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(italicBtn)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(copyBtn)
                                .addComponent(cutBtn)
                                .addComponent(pasteBtn)
                                .addComponent(boldBtn)
                                .addComponent(jLabel14)
                                .addComponent(jLabel13)
                                .addComponent(jLabel15)
                                .addComponent(jLabel17)
                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fontCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sizeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(choosecolor_button))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 530, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choosecolor_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosecolor_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choosecolor_buttonActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // SALIR

        try {
            data.text = textEditor.getText();
            this.setVisible(false);
            Logica.saveFile(data.currentFile.getCanonicalPath(), data);
            new menu().setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jLabel1MouseClicked

    private void copyToClip(String text) {
        Clipboard clip = Toolkit.getDefaultToolkit().getSystemClipboard();
        StringSelection strse1 = new StringSelection(text);
        clip.setContents(strse1, strse1);
    }

    private void cutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cutBtnMouseClicked
        // TODO add your handling code here:
        System.out.println("CORTADO");
        String selectedText = textEditor.getSelectedText();
        String newText = textEditor.getText().replace(selectedText, "");
        textEditor.setText(newText);
        copyToClip(newText);
    }//GEN-LAST:event_cutBtnMouseClicked

    private void copyBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_copyBtnMouseClicked
        // TODO add your handling code here:
        copyToClip(textEditor.getSelectedText());
    }//GEN-LAST:event_copyBtnMouseClicked

    private void pasteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pasteBtnMouseClicked
        // TODO add your handling code here:

        Clipboard clip = Toolkit.getDefaultToolkit().getSystemClipboard();
        Transferable t = clip.getContents(null);

        try {

            if (t.isDataFlavorSupported(DataFlavor.stringFlavor)) {
                String pasteText = (String) t.getTransferData(DataFlavor.stringFlavor);
                textEditor.setText(textEditor.getText() + pasteText);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_pasteBtnMouseClicked

    private void fontComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fontComboItemStateChanged
        // TODO add your handling code here:
        if (!enabled) {
            return;
        }
        
        int style = Font.PLAIN;
        if (data.bold == true) {
            style = Font.BOLD;
            System.out.println("nueva fuente | bold");
        }
        if (data.italic == true) {
            System.out.println("nueva fuente | italic");
            style = Font.ITALIC;
        }
        
        Font newFont = new Font((String) fontCombo.getSelectedItem(), style, data.fontSize);
        textEditor.setFont(newFont);
        
        data.fontName = (String) fontCombo.getSelectedItem();
    }//GEN-LAST:event_fontComboItemStateChanged

    private void boldBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boldBtnMouseClicked
        // TODO add your handling code here:
        if (data.bold == false) {
            data.italic = false;
            Font newFont = new Font(textEditor.getFont().getName(), Font.BOLD, data.fontSize);
            data.bold = true;
            textEditor.setFont(newFont);
        } else {
            data.bold = false;
            Font newFont = new Font(textEditor.getFont().getName(), Font.PLAIN, data.fontSize);
            textEditor.setFont(newFont);
        }
    }//GEN-LAST:event_boldBtnMouseClicked

    private void italicBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_italicBtnMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_italicBtnMouseEntered

    private void italicBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_italicBtnMouseClicked
        // TODO add your handling code here:
        if (data.italic == false) {
            data.bold = false;
            Font newFont = new Font(textEditor.getFont().getName(), Font.ITALIC, data.fontSize);
            data.italic = true;
            textEditor.setFont(newFont);
        } else {
            data.italic = false;
            Font newFont = new Font(textEditor.getFont().getName(), Font.PLAIN, data.fontSize);
            textEditor.setFont(newFont);
        }
    }//GEN-LAST:event_italicBtnMouseClicked

    private void sizeComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sizeComboItemStateChanged
        // TODO add your handling code here:
        int newSize = Integer.parseInt((String) sizeCombo.getSelectedItem());

        int style = Font.PLAIN;
        if (data.bold == true) {
            style = Font.BOLD;
            System.out.println("nueva size | bold");
        }
        if (data.italic == true) {
            System.out.println("nueva size | italic");
            style = Font.ITALIC;
        }

        Font f = textEditor.getFont();
        Font newFont = new Font(f.getName(), style, newSize);
        textEditor.setFont(newFont);
        data.fontSize = newSize;

    }//GEN-LAST:event_sizeComboItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editortexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editortexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editortexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editortexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editortexto(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel boldBtn;
    private javax.swing.JButton choosecolor_button;
    private javax.swing.JLabel copyBtn;
    private javax.swing.JLabel cutBtn;
    private javax.swing.JComboBox<String> fontCombo;
    private javax.swing.JLabel italicBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pasteBtn;
    private javax.swing.JComboBox<String> sizeCombo;
    private javax.swing.JTextArea textEditor;
    // End of variables declaration//GEN-END:variables
}
